## Working with Numpy - For Mathematical Operations

In [7]:
import numpy as np

In [8]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))
print(a.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [9]:
b = np.array([[1],[2],[3],[4],[5]])
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [10]:
c = np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)
print(c[1][1])

[[1 2 3]
 [4 5 6]]
(2, 3)
5


In [11]:
# Create Zeros Array
a = np.zeros((3,3))
print(a) 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
#Create Ones Array
b = np.ones((2,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
#Array of some constants
c = np.full((3,2),5)
print(c)

[[5 5]
 [5 5]
 [5 5]]


In [14]:
#Identity Matrix - Size/Square Matrix
d = np.eye(4)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
#Random Matrix
randomMatrix = np.random.random((2,3))
print(randomMatrix)

[[0.40649136 0.86088693 0.75894584]
 [0.22095604 0.20588059 0.4018149 ]]


In [16]:
#To Read the matrix 
print(randomMatrix[:,1])

[0.86088693 0.20588059]


In [17]:
#SLicing
randomMatrix[1,1:3] = 1
print(randomMatrix)

[[0.40649136 0.86088693 0.75894584]
 [0.22095604 1.         1.        ]]


In [18]:
#SEt some rows and columns with any values
z = np.zeros((3,3))
print(z)
z[1,:] = 5
z[ :,-1] = 7
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 7.]
 [5. 5. 7.]
 [0. 0. 7.]]


In [19]:
#Datatypes
print(z.dtype)

float64


In [20]:
#Mathematical Operations

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

#Element wise addition
print(x+y)
print(np.add(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [21]:
print(x-y)
print(np.subtract(x,y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [22]:
print(x*y)
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [23]:
print(x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [24]:
print(np.sqrt((x)))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [25]:
#Matrix Multiplication / Dot Products
print(x)

[[1 2]
 [3 4]]


In [26]:
print(y)

[[5 6]
 [7 8]]


In [27]:
print(x.dot(y))

[[19 22]
 [43 50]]


In [28]:
print(np.dot(x,y))

[[19 22]
 [43 50]]


In [29]:
#Multiplication(Dot Products) of Vectors ===> Scalar
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(a.dot(b))

30


In [30]:
print(a)

[1 2 3 4]


In [31]:
print(sum(a))

10


In [32]:
print(x)

[[1 2]
 [3 4]]


In [33]:
print(np.sum(x))

10


In [34]:
print(np.sum(x,axis=0))

[4 6]


In [35]:
#Stacking of arrays
print(a)
b = b**2
print(b)

[1 2 3 4]
[ 1  4  9 16]


In [36]:
a = np.stack((a,b),axis=0)

In [37]:
#Reshape a Numpy Array
print(a)

[[ 1  2  3  4]
 [ 1  4  9 16]]


In [38]:
a = a.reshape((4,2))
print(a)

[[ 1  2]
 [ 3  4]
 [ 1  4]
 [ 9 16]]


## Nump Random Module

- rand: Random values in a given shape.
- randn: Rrturn a sample (or samples) from the "standard normal" distribution.
- randint: Return random integers from low (inclusive) to high (exclusive).
- random: Return random floats in the half-open interval (0.0, 1.0)
- choice: Generates a random sample from a given 1-D array 
- Shuffle: Shuffles the contents of a sequence

In [39]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [40]:
np.random.shuffle(a)
print(a)

[9 2 6 0 3 4 7 8 1 5]


In [43]:
#Returns values from Standard Normal Distributions
a = np.random.rand(2,3)
print(a)

a = np.random.randint(5,10,3)
print(a)

#Randomly pick one element from a array
element = np.random.choice([1,4,3,2,11,27])
print(element)

[[0.54383736 0.68867295 0.54306541]
 [0.20052513 0.18410101 0.79910549]]
[8 5 9]
2


## Some mOre Numpy Functions - Statistics

- min, max
- mean
- median
- average
- variance
- standard devidation

In [50]:
a = np.array([[1,2,3,4],[7,6,2,0]])
print(a)
print(np.min(a))

#Specify axis for the direction in case of mulidim array
print(np.min(a,axis=0))
print(np.min(a,axis=1))

[[1 2 3 4]
 [7 6 2 0]]
0
[1 2 2 0]
[1 0]


In [52]:
b = np.array([1,2,3,4,5])
m = sum(b)/5
print(m)

print(np.mean(b))
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

3.0
3.0
[4.  4.  2.5 2. ]
[2.5  3.75]


In [53]:
#median - middle most value

c = np.array([1,5,4,2,0])
print(np.median(c))

2.0


In [54]:
#Mean vs Average
c = np.array([1,5,4,2,0])
print(np.mean(c))

2.4


In [56]:
#Weights
w = np.array([1,1,1,1,1])
print(np.average(c,weights=w))

2.4


In [57]:
#Standard Deviation deonted by Sigma 
u = np.mean(c)
myStd = np.sqrt(np.mean(abs(c-u)**2))
print(myStd)

1.854723699099141


In [60]:
#Inbuilt Function
u = np.std(c)
myStd = np.sqrt(np.mean(abs(c-u)**2))
dev = np.std(c)
print(dev)

1.854723699099141


In [59]:
#Variance is Sigma square
u = np.std(c)
myStd = np.sqrt(np.mean(abs(c-u)**2))
print(myStd**2)
print(np.var(c))

3.737326244324124
3.4400000000000004
